Team-Blitz-Steady/steady-client

.prettierrc, package.json, pnpm-lock.yaml, src/app/layout.tsx, src/components/_common/Dropdown/index.tsx, tailwind.config.js
- tailwind 설정에 Steady 메인 색상 정보 추가
```tsx
<Dropdown children={<Avatar size={"3"} radius={"full"} src={"https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?&w=256&h=256&q=70&crop=focalpoint&fp-x=0.5&fp-y=0.3&fp-z=1&fit=crop"} fallback={'A'}/>} options={[{label:'마이페이지', linkTo:'/mypage'}, {label: '로그아웃', linkTo: '/logout'} ]} />
```
위 코드를 pages.tsx에서 렌더링하면 아래처럼 작동하는 컴포넌트를 볼 수 있습니다!
- 드롭다운 메뉴를 클릭하면 children 주변의 색깔이 변하는데, 이걸 그대로 둬도 괜찮은지 궁금하네여
#10
=> ✨ Feat: #10 Dropdown 공통 컴포넌트 추가

src/components/_common/ListItem/index.tsx
위: 내 스테디 목록 페이지의 ListItem
아래: 내 신청서 양식 페이지의 ListItem
- 사용시
```ts
// 임시 data
const steadyInfo = [
{
title: "내가 만든 스터디임",
createdAt: "2023.10.25",
isAdmin: true,
},
{
title: "참여한 스터디임",
createdAt: "2023.10.25",
isAdmin: false,
},
];
const formInfo = [
{
title: "내가 만든 스터디 폼 양식",
createdAt: "2023.10.25",
isAdmin: true,
},
{
title: "내가 참여한 스터디 폼 양식",
createdAt: "2023.10.25",
isAdmin: false,
},
];
<ListItem
object={steadyInfo}
className="w-1000"
listType="steady" // steady or from 구분 ( 아이콘 다르게 렌더링)
/>
<ListItem
object={formInfo}
className="w-750"
listType="form"
/>
```
- Icon 컴포넌트가 없어서 임시로 사용했습니닷
- Line 컴포넌트가 없어서 임시로 border를 사용했습니다. 
이후 사진 캡쳐후 삭제 했습니다.
#3
=> ✨ Feat: #3 - 공통 컴포넌트 ListItem 추가

src/app/page.tsx, src/components/_common/Icon/index.tsx
- 사용시
- icon 이름을 일일이 props로 줘야하기 때문에 이름 규칙을 만드는 것도 괜찮을 것 같습니다.
#11
=> ✨ Feat: #11 - 공통 컴포넌트 Icon 추가

src/components/_common/ListItem/index.tsx
- 사용
```ts
import ListItem from "@/components/_common/ListItem";
const steadyInfo = [
{
title: "내가 만든 스터디임",
createdAt: "2023.10.25",
isAdmin: true,
},
{
title: "참여한 스터디임",
createdAt: "2023.10.25",
isAdmin: false,
},
];
const formInfo = [
{
title: "내가 만든 스터디 폼 양식",
createdAt: "2023.10.25",
isAdmin: true,
},
{
title: "내가 참여한 스터디 폼 양식",
createdAt: "2023.10.25",
isAdmin: false,
},
];
export interface SteadyInfoType {
title: string;
createdAt: string;
isAdmin: boolean;
}
const Home = () => {
return (
<main>
<div>This is Main</div>
<ListItem
object={steadyInfo}
listType="steady"
/>
<h1 className="text-3xl font-bold underline">Hello, Steady!</h1>
<ListItem
object={formInfo}
listType="form"
/>
</main>
);
};
export default Home;
```
close #40
=> 🔨 Refactor(#40): Icon 컴포넌트 적용, width도 조건부 적용

src/app/layout.tsx, tailwind.config.js
- 현재 헤더가 일정 너비 이상에서 로고와 버튼 사이 간격이 고정되는 스타일이 빠져있는데, 나중에 추가하도록 하겠습니다!
close #48
=> 🚨 Style(#48) Root Layout 공통 스타일 및 헤더 적용

package.json, pnpm-lock.yaml, src/components/_common/Avatar/index.tsx
ex) 이런 이미지를 Avatar src로 등록해도
위와 같이 원형으로 구현됨
```jsx
<Avatar
src={"/images/c1.png"} // 올바른 경로는 /images/ci.png
size={80}
alt={"S"}
/>
```
위와 같이 prop value를 보여줌
- Next Image 컴포넌트를 Radix UI의 AvatarPrimitive의 자식으로 넘기려 했는데 원형 유지가 안되는 문제가 있어서 해당 아이디어 폐기
- 따라서 현재는 Next Image 컴포넌트를 활용하고 있지 않음
close #55
=> 🚨 Fix(#55): Avatar 컴포넌트 에러 수정 외 1건

src/components/_common/HashTagInput/index.tsx, src/components/ui/toast.tsx
=> ✨ Feat(#88): HashTagInput 컴포넌트 추가

src/app/layout.tsx, src/lib/react-query/QueryProvider.tsx
- useQuery 훅을 사용하는 컴포넌트는 클라이언트 컴포넌트여야합니다!
- 예제 코드 : client/page.tsx
```tsx
"use client";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
interface TodoType {
userId: number;
id: number;
title: string;
completed: boolean;
}
const ClientPage = () => {
const { data, isPending, error } = useQuery<{ data: TodoType[] }>({
queryKey: ["todos"],
queryFn: () => axios.get("https://jsonplaceholder.typicode.com/todos"),
});
if (isPending) {
return <div>loading...</div>;
}
if (error) {
return <div>Error! {error.message}</div>;
}
return (
<div>
{data.data.map((todo) => (
<div key={todo.id}>{todo.title}</div>
))}
</div>
);
};
export default ClientPage;
```
close #117
=> ✨ Feat(#117): Query Client 생성 및 Provider 적용

src/app/(steady)/steady/detail/[id]/page.tsx, src/components/Posts/index.tsx, src/components/_common/Tag/index.tsx, src/services/steady/getSteadyDetails.ts, src/services/types/index.ts
- 상세 페이지에서 useQuery로 `getSteadyDetails` 사용시
```ts
const { data: steadyDetailsData } = useQuery({
queryKey: ["steadyDetails"],
queryFn: () => getSteadyDetails(params.id),
});
{steadyDetailsData && <Tag status={steadyDetailsData.status} />}
```
close #126
=> ✨ Feat(#126): 스테디 상세 페이지 api 연동 

src/services/steady/finishSteady.ts
- 사용예시
```ts
// params.id는 스테디 id 입니다.
<button onClick={() => finishSteady(params.id)}>스테디 종료</button>
```
close #128
=> ✨ Feat(#128): 스테디 종료 api 연동

src/services/steady/promoteSteady.ts
- 현재 promoteSteady api는 호출 할 때마다 끌어올리기 횟수가 차감되도록 백엔드 쪽에 구현되어있는 것 같습니다.
- 따라서 프론트 쪽에서 스테디 상세 정보 받아올 때, validation이 필요할 것 같습니다. (0 이면 더 이상 누르지 못하도록)
- 사용예시
```ts
// params.id는 스테디 id
<button onClick={() => promoteSteady(params.id)}>끌어올리기</button>
```
close #129
=> ✨ Feat(#129): 스테디 끌어올리기 api 연동

src/app/(steady)/steady/applicant/[id]/page.tsx, src/services/application/getApplicationDetails.ts, src/services/types/index.ts
- postman
- 신청자 목록 및 답변 열람 페이지 & Network 요청
close #144
=> ✨Feat(#144): 신청서 상세 조회 api 연동

src/app/(steady)/steady/create/loading.tsx, src/app/(steady)/steady/create/page.tsx, src/services/steady/getPositions.ts, src/services/steady/getStacks.ts, src/services/types/index.ts
- 해당 내용 TODO 주석으로 남겼습니다
close #167
=> ✨ Feat(#167): 스테디 생성 페이지에 기술 스택, 모집 분야 요청 API 적용

src/app/(steady)/steady/edit/[id]/page.tsx, src/app/(steady)/steady/edit/questions/[id]/loading.tsx, src/app/(steady)/steady/edit/questions/[id]/page.tsx, src/services/steady/getSteadyQuestions.ts, src/services/steady/updateSteady.ts, src/services/steady/updateSteadyQuestions.ts, src/services/types/index.ts
- 질문 수정에 성공하면 해당 스테디의 모집글 상세 페이지로 이동합니다!
- 딱히 없습니다! 질문 수정이 어제 새벽엔 안되던데 오늘 아침에 되니까 신기하네요..
close #176
=> ✨ Feat(#176): 스테디 질문 수정 페이지 api 연동

src/app/(steady)/steady/detail/[id]/page.tsx, src/services/steady/getSteadyQuestions.ts, src/services/types/index.ts
- 일단 디자인이 없어서 데이터만 넣은 느낌입니다 ㅎㅎ ㅠ
- 시작하기 전엔 몰랐는데 이거 뭐 너무 규모가 작은 작업이었네요 하핫...😅
close #175
=> ✨ Feat(#175): 상세 페이지에 신청서 보기 API 연동

src/app/(auth)/login/route.ts, src/app/(auth)/logout/route.ts, src/components/_common/Modal/LoginModal/index.tsx
- 리다이렉트 방식을 NextResponse.redirect -> `next/navigation`의 redirect를 반환
close #190
=> 🔥🚨 Fix(#190): 쿠키 에러 1차 핫픽스

src/app/(steady)/steady/create/page.tsx, src/app/(steady)/steady/create/questions/page.tsx, src/components/_common/Selector/Date/index.tsx, src/stores/createSteadyData.ts, src/utils/isPastDate.ts
- 전역 상태 키 값이 원래 `create-steady-key` 였는데 스테디 정보를 담는 상태라서 `steadyState`로 변경했습니다!
close #182
=> 🚨 Fix(#182): 스테디 등록 페이지 1차 QA 반영

src/app/(steady)/steady/create/page.tsx, src/app/(steady)/steady/create/questions/page.tsx, src/components/_common/Input/index.tsx, src/constants/create-steady.ts
- 질문 등록 페이지의 경우 스테디 등록 페이지로 돌아가도록 했습니다! 그런데 작성하던 데이터는 보이지 않습니다...?
- 스테디 등록 페이지의 경우 취소 버튼 클릭 시 작성 중인 데이터의 삭제 및 메인 페이지로 이동됨을 안내하며, 돌아가기 버튼 클릭 시 로컬 스토리지에 있을 수 있는 데이터를 지우고 메인 페이지로 이동시키게 됩니다.
- [1e1358f](https://github.com/Team-Blitz-Steady/steady-client/commit/1e1358f2b48d98f85654bb638341361e3f81e915) 커밋 메시지에서 스테디 `생성` 페이지라고 작성했네요 ㅠㅠ 별도의 페이지가 있는 것이 아니라 본문에서 언급 중인 등록 페이지가 맞습니다..
- 기존 헤딩 문구 데이터는 스테디 수정 페이지에서도 사용 중이기 때문에, 해당 페이지의 외형을 변경할 때 삭제될 예정입니다.
- 일단 어디까지나 외형 변경이 메인이었던 이슈여서 추가한 취소 기능의 엣지 케이스 대응은 추후 이슈 생성 후 진행하겠습니다!
- 스테디 수정 페이지 외형 또한 금방 변경해서 PR 올리겠습니다!
close #199
=> 💄 Style(#199): 스테디 등록 페이지 디자인 변경

src/app/(auth)/api/logout/route.ts
- header의 "Set-Cookie"는 원래 string만 받을 수 있도록 TS에서 정의해둔거같은데, string[]로 넘겼을 때 개발환경에서 의도한대로 다수의 "Set-Cookie"가 응답으로 날아오는것을 확인해 일단 `// @ts-expect-error`로 해당 TS 에러를 무시하였습니다.
잘 동작했으면 좋겠네요!
close #207
=> 🚨 Fix(#207): 로그아웃 실패 시 직접 쿠키 만료 헤더 응답 전송

src/components/_common/AppBar/index.tsx, src/components/ui/scroll-area.tsx
- TODO: 알림이 없으면 "아직 도착한 알림이 없어요! 😀 " 같은 대체 UI를 표시하는 기능을 생각하고 있는데 추후 추가하겠습니다!
- TODO: 현재 알림창 사이에 구분선이 없는데, 1차 QA 이후 추가하도록 하겠습니다.
- TODO: 알림은 유저가 사이트를 이용 중인 상황에도 발생할 수 있기 떄문에, 일정 Interval 또는 페이지 전환 시 refetch를 할 수 있도록 변경하려고 합니다!
- ScrollArea에서 스크롤바를 숨기고 싶은 상황이 몇 번 있었는데, 이번이 특히 그래서 새로운 Prop을 받도록 변경했습니다!
```jsx
// ...
<ScrollArea
className={"h-full w-full rounded-md"}
scrollBarClassName={"hidden"}
>
// ...
```
위와 같이 `ScrollArea` 컴포넌트에 scrollBarClassName Prop으로 className을 전달할 수 있습니다!
close #214
=> ✨ Feat(#214): 알림 기능 구현

src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx, src/app/(steady)/steady/applicant/[steady_id]/layout.tsx, src/app/(steady)/steady/applicant/[steady_id]/page.tsx, src/hooks/query/useApplicantListQuery.ts, src/services/application/getApplicantList.ts, src/services/types/index.ts
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/ab90d9e4-9c88-4e4c-b1f4-98aa5e1450ef
`getquerydata` 로 query 키 값으로 데이터를 불러오려고 했는데, undefined가 발생해서..ㅠ 일단은 `useApplicantListQuery`를 다시 불러오는 방식으로 수정했습니다.
close #225
=> 🚨Hotfix(#225): 신청자 목록 및 답변 열람 페이지 버그 수정

src/app/(user-menu)/mypage/reviews/page.tsx
=> 💄 Style(#227): 백엔드 수정 사항 반영

src/app/(steady)/steady/create/questions/page.tsx, src/app/(steady)/steady/edit/questions/[id]/page.tsx
- 두 사이트의 질문 데이터 식별자가 달라서 구현 방식은 조~금 다르지만 cmdk의 Command 컴포넌트에서 Enter 키보드 입력을 감지하고 질문 추가 함수를 실행하는 것과, useEffect 훅을 활용해서 자동 포커스 시켜주는 로직은 결이 같습니다!
close #219
=> ✨ Feat(#219): 질문 등록 / 수정 페이지 질문 추가 기능 개선

src/app/(auth)/api/login/route.ts, src/app/(user-menu)/mypage/page.tsx, src/app/layout.tsx, src/components/_common/Input/index.tsx, src/components/_common/Modal/LoginModal/LoginStepsContents/SetPositionAndStacks.tsx, src/schemas/setNickname.ts, src/schemas/userBioSchema.ts, src/services/user/deleteMyProfile.ts, src/services/user/updateMyProfile.ts
=> ✨ Feat(#239): 내 프로필 페이지 API 연동

src/app/(steady)/steady/create/questions/page.tsx, src/app/(steady)/steady/edit/questions/[id]/page.tsx, src/constants/selectorItems.ts
=> ✨ Feat(#256): 질문 등록 / 수정 페이지 템플릿 정보 불러오기 / 질문 템플릿으로 저장하기 기능 추가

src/app/(user-menu)/mypage/template/create/page.tsx, src/app/(user-menu)/mypage/template/edit/[id]/page.tsx, src/app/(user-menu)/mypage/template/page.tsx, src/components/TabBar/index.tsx
=> 💄 Style(#291): 템플릿 페이지 반응형 작업

src/app/(steady)/steady/detail/[id]/page.tsx, src/app/error.tsx
=> 🚨 Fix(#298): 상세 페이지 좋아요 api 수정 및 에러 페이지 새로고침 버튼 추가

src/components/_common/AppBar/index.tsx, src/components/_common/Dropdown/index.tsx, src/components/_common/Editor/InitializedMDXEditor.tsx, src/components/_common/NotificationPopup/index.tsx, src/components/_common/Selector/Multi/index.tsx
- MultiSelector 이슈는 주말에 찾아서 고치겠습니닷..
close #300
=> 🚨 Fix(#300): 3차 QA 부분 수정

src/app/(steady)/steady/review/[id]/page.tsx
=> 💄 Style(#302): 리뷰 페이지 반응형 작업

src/app/(steady)/steady/detail/[id]/page.tsx, src/app/(user-menu)/mysteady/page.tsx, src/components/_common/ContactTag/index.tsx, src/hooks/useCopySteadyContact.ts
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/883595d5-50c9-45cd-8402-a18368563cd9
close #313
=> ✨Feat(#313): 스테디 상세 페이지에 연락수단 클립보드 기능 추가

src/app/(user-menu)/mypage/page.tsx, src/app/error.tsx, src/components/_common/Dropdown/index.tsx, src/components/_common/Input/index.tsx, src/components/_common/NotificationPopup/index.tsx, src/components/_common/ProfileImageUpload/index.tsx
=> 🚨 Fix(#319): 4차 QA 사항 반영

src/app/page.tsx, src/components/_common/Modal/LoginModal/index.tsx, src/components/_common/Modal/WelcomeModal/WelcomeModalContainer.tsx, src/components/_common/Modal/WelcomeModal/index.tsx, src/stores/welcomeModalOpen.ts
=> ✨ Feat(#324): 로그인 온보딩  웰컴 모달 구현

src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
=> 🚨 Fix(#326): 템플릿 오류 수정

src/app/(steady)/steady/create/page.tsx, src/app/(steady)/steady/create/questions/page.tsx, src/stores/createSteadyData.ts
=> 🚨 Fix(#347): 스테디 등록 과정 데이터 유실 오류 수정
