tailwind.config.js
=> 💄 Style: tailwind.config에 색상 정보 추가

src/app/layout.tsx
=> 💄 Style: Inter 폰트 루트 레이아웃에 적용

tailwind.config.js
=> 💄 Style: 자주 사용하는 CSS 속성 rem -> px 변환 설정 추가

next.config.js, src/app/page.tsx, src/components/_common/Avatar/index.tsx
- 원격에서 이미지 소스를 불러올 때에는 next.config.js에 아래와 같은 설정을 추가해야합니다!
```js
images: {
remotePatterns: [
{
protocol: "https",
hostname: "images.unsplash.com", // 이미지가 위치한 원격 호스트 endpoint
},
],
},
```
- src, size 두 개의 Prop을 받으며, size의 단위는 px입니다.
#12
=> ✨ Feat: #13 Avatar 공통 컴포넌트 추가

src/components/_common/Spinner/index.tsx
- size 값을 Prop으로 받으며, small, medium, large 3가지 size 유형이 존재합니다
#13
=> ✨ Feat: #13 Spinner 공통 컴포넌트 추가

src/components/_common/Button/index.tsx
- 사용 방법
```ts
import Button, { buttonSize } from "@/components/_common/Button";
<Button className={`${buttonSize.xl} bg-st-primary`}>스테디 등록</Button>
<Button className={`${buttonSize.lg} bg-st-green`}>완료</Button>
<Button className={`${buttonSize.md} bg-st-red`}>스테디 종료</Button>
<Button className={`${buttonSize.sm} bg-white`}>취소</Button>
```
```ts
export const buttonSize = {
xl: "w-165 h-50 rounded-6", // 스테디 등록
lg: "w-140 h-50", 
md: "w-115 h-50",
sm: "w-90 h-35", 
};
```
#6
=> ✨ Feat: #6 - 공통 컴포넌트 Button 추가

src/components/_common/Button/index.tsx
- className 뿐만 아니라 button 속성에 대한 props를 자유롭게 받을 수 있도록 했습니다.
#38
=> ✨ Feat: #38 - 공통 컴포넌트 Button props 추가

.husky/commit-msg, commitlint.config.js, package.json, pnpm-lock.yaml, src/app/page.tsx
conventional commit의 구조는 일반적으로 아래와 같습니다
```
<type>(scope?): subject
```
이 구조에 따라 lint는 아래와 같은 과정을 거쳐 진행됩니다.
- type: emoji + type(Pascel case)로 이루어져 있는지 체크
```
🚨 Fix:         [파일 명.tsx] - [수정 내용]
✨ Feat:	새로운 기능 추가, 사용자 입장에서 변화가 있을 경우
🎉 Init:	프로젝트 초기 생성
📝 Chore:	그 외 자잘한 수정에 대한 커밋, 주석, 의존성 설치, 리드미 수정
💄 Style:	CSS, styled-component 스타일 관련 변경
🔨 Refactor:	코드 리팩토링에 대한 커밋, 사용자 입장에서 변화가 없는 코드, 파일명 폴더명 변경 및 이동
🗑️ Remove:	파일을 삭제하는 작업만 수행하는 경우
```
- scope: 소괄호쌍 '( )'에 감싸져있고, #<issue-number>의 형태인지 체크
- subject: 내용 자체는 검사하지 않음. 다만 `<type>(scope?): subject`의 전체 길이가 100을 넘지 않는지 체크
그래서 변경된 커밋 메시지 컨벤션은 아래와 같습니다
```
Emoji Type(#issue-num): subject
// ex) 🚨 Fix(#41): commitlint 이슈 해결
```
- commitlint 외 라이브러리와 플러그인을 추가했습니다!
- commitlint-config-gitmoji …
=> 🚨 Fix(#41): commitlint 이슈 해결

src/app/(steady)/(application)/application/layout.tsx, src/app/(steady)/(application)/application/submit/[id]/page.tsx, src/components/application/Question.tsx, src/components/application/Title.tsx, src/components/application/index.ts
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/f9f9b5bb-64c6-4675-8bff-e0ebf0a63225
- 질문 개수가 적을 때, 버튼 위치가 괜찮을까요?
close #61
=> ✨ Feat(#61): 신청서 작성 페이지 1차 구현

src/components/_common/StickyButton/index.tsx
=> 💄 Style(#69): 공통 컴포넌트 Stickybutton position 코드 제거

src/components/_common/Input/index.tsx
=> ✨ Feat(#98): 공통 컴포넌트 Input props 자동완성 기능 구현

src/components/_common/Icon/index.tsx
=> ✨ Feat(#97): 공통 컴포넌트 Icon props 자동완성 기능 구현

src/app/(user-menu)/mypage/page.tsx, src/app/(user-menu)/mypage/reviews/page.tsx
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/2f3ba1c8-31d8-4583-af97-08689806fb14
- TODO: 무한스크롤 구현, 프로필 클릭시 유저 모달, 아이콘 임시
close #93
=> ✨ Feat(#93): 내가 받은 리뷰 페이지 1차 구현

package.json, pnpm-lock.yaml, src/components/_common/AppBar/index.tsx, src/components/_common/Dropdown/index.tsx, src/components/ui/scroll-area.tsx
- 반응형은 미구현
- 지금 알림 목록 Hydration 과정에서 뭔가 문제가 있는 것 같은데 아직 수정 못했습니다.. 테스트 통과 못하면 수정할게용
close #104
=> ✨ Feat(#104): AppBar 기능 추가

src/app/(steady)/steady/create/questions/page.tsx, src/app/layout.tsx, src/components/ui/use-toast.ts
=> ✨ Feat(#107): 스테디 질문 등록 페이지 구현

src/services/oauth/kakao/getKakaoToken.ts, src/services/types/index.ts
=> ✨ Feat(#130): 타입 폴더 생성 및 카카오 토큰 타입 정의

src/services/index.ts, src/services/oauth/kakao/getKakaoLoginURL.ts, src/services/oauth/kakao/getKakaoToken.ts, src/utils/cookies.ts
- 추후에 deleteCookies에 대해서 Promise를 감싸줘야 할 수도 있습니다
close #122
=> ✨ Feat(#122) Axios 인스턴스에 auth interceptor 적용

src/services/steady/deleteSteady.ts
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/0e22ebe6-7076-4288-a3ec-c7f20c02dfb4
- 사용시
```ts
// params.id는 스터디 id를 의미
<button onClick={() => deleteSteady(params.id)}>클릭</button>
```
close #127
=> ✨ Feat(#127): 스테디 삭제 api 연동

src/middleware.ts, src/utils/cookies.ts
| HTTP Only 속성이 추가된 쿠키는 JavaScript를 통해 접근할 수 없고 Client Side에서 수정할 수 없어 보안성이 향상됩니다
- 토큰의 유효성은 검사하지 않습니다... 서버에 유효성 검증 요청을 하지 않으므로, 추가 보안 로직이 필요합니다.
close #123
=> ✨ Feat(#123): Private Route 설정

src/components/_common/AppBar/index.tsx
- Icon 버튼을 제거했습니다!
- 매우 간단한 에러..!
- Icon 버튼을 제거해서 고쳤습니다!
- 매우 간단한 에러..!
close #136
=> 🚨 Fix(#136): 알림 Popover UI에 의한 에러 픽스

src/app/(steady)/steady/edit/questions/[id]/page.tsx
=> ✨ Feat(#108): 질문 수정 페이지 구현

src/app/(steady)/steady/applicant/layout.tsx, src/services/application/changeApplicationStatus.ts, src/services/types/index.ts, src/utils/extractValue.ts
=> ✨ Feat(#151): 신청서 상태 변경 api 연결

src/app/(user-menu)/mypage/application/page.tsx, src/app/(user-menu)/mypage/layout.tsx, src/components/_common/SideBar/index.tsx
https://github.com/Team-Blitz-Steady/steady-client/assets/61570018/bb64baa7-6fa8-4217-bdcb-03294ea9dd21
close #170
=> ✨ Feat(#170): 내 신청서 관리 페이지 구현

src/components/_common/Modal/LoginModal/LoginStepsContents/SetPositionAndStacks.tsx, src/components/_common/Modal/LoginModal/index.tsx, src/services/steady/getPositions.ts, src/services/steady/getStacks.ts, src/services/types/index.ts, src/services/user/createUserProfile.ts, src/services/user/getMyProfile.ts, src/services/user/getUserProfile.ts, src/services/user/updateMyProfile.ts, src/stores/newUserInfo.ts
- 내 프로필 조회: getMyProfile
- 타인의 프로필 조회: getUserProfile
- 프로필 수정: updateMyProfile
에러수정
- 유저 프로필 생성 api에서 stackIds가 stacksId로 변경되었다구해서 백엔드 요청사항 같이 반영했습니다.
close #192
=> ✨Feat(#192): 유저 관련 api 

src/services/notification/deleteAllNotifications.ts, src/services/notification/deleteNotification.ts, src/services/notification/getAllNotifications.ts, src/services/notification/readAllNotifications.ts, src/services/notification/readNotification.ts, src/services/types/index.ts
- 전체 알림 조회: getAllNotifications
- 모든 알림 읽기: readAllNotifications
- 알림 읽기: readNotification
- 모든 알림 삭제: deleteAllNotifications
- 알림 삭제: deleteNotification
close #195
=> ✨ Feat(#195): 알림 관련 api 

src/app/(user-menu)/mypage/template/create/page.tsx, src/app/(user-menu)/mypage/template/edit/[id]/page.tsx, src/app/(user-menu)/mypage/template/page.tsx
https://github.com/Team-Blitz-Steady/steady-client/assets/61570018/973b398a-9e99-4ae0-a693-1c6456f8c480
- 브랜치 네임을 잘못 설정했네요...ㅜㅜ
close #201
=> ✨ Feat(#201): 템플릿 삭제 버튼 생성 및 삭제 이슈 해결

src/app/(steady)/steady/review/[id]/page.tsx, tailwind.config.js
=> ✨ Feat(#202): 리뷰 페이지 스테디 정보 추가

src/app/(steady)/steady/edit/[id]/page.tsx, src/constants/create-steady.ts
- 취소 버튼은 따로 '수정을 취소할까요?' 의사를 묻진 않는데 묻게 하는게... 나을까요?
close #206
=> 💄 Style(#206): 스테디 수정 페이지 외형 변경

src/app/(user-menu)/mypage/template/create/page.tsx, src/app/(user-menu)/mypage/template/page.tsx
=> 🚨 Fix(#218): 템플릿 생성 이슈

src/app/(steady)/steady/edit/[id]/page.tsx
- onSubmit 함수의 비동기 로직 처리 문법을 프로미스 체이닝 -> async / await으로 변경하였습니다!
close #229
=> 🚨 Fix(#229): 스테디 수정 페이지 핫픽스

src/app/(user-menu)/mypage/template/create/page.tsx, src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
=> ✨ Feat(#257): 템플릿 페이지 취소하기 버튼 추가

src/app/(user-menu)/mypage/application/page.tsx, src/services/types/index.ts
=> 🔨 Refactor(#262): 내 신청서 페이지 리팩터링

package.json, pnpm-lock.yaml, src/app/(steady)/steady/create/questions/page.tsx, src/app/(steady)/steady/edit/questions/[id]/page.tsx, src/app/(steady)/steady/manage/[id]/page.tsx, src/app/(user-menu)/mypage/page.tsx, src/components/_common/ProfileImageUpload/index.tsx, src/components/ui/accordion.tsx, src/services/types/index.ts, src/services/user/getProfileImageLink.ts
=> ✨ Feat(#260): 프로필 이미지 수정 기능 구현

src/app/(user-menu)/mysteady/page.tsx, src/app/page.tsx, src/components/_common/NavigationBar/index.tsx
- 사용시
```ts
max-sm:px-20 
sm:px-20 
md:px-30 
lg:px-50 
xl:px-50
요렇게 5가지로 반응형 구현하시면 될 것 같습니당!
```
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/c004cd80-476f-438d-aba4-bbc2f8e218b2
close #268
=> 💄Style(#268): 내 스테디 페이지 반응형 구현

src/app/(steady)/steady/detail/[id]/page.tsx
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/97c55187-6952-4b4d-a4fb-376727dc7e8d
close #267
=> 💄 Style(#267): 상세 페이지 반응형 구현

src/app/(user-menu)/mypage/page.tsx, src/app/error.tsx, src/components/_common/Input/index.tsx, src/react-query.d.ts, src/services/types/index.ts
=> 🚨 Fix(#270): 2nd QA 사항 반영

src/app/(user-menu)/mypage/template/page.tsx, src/components/_common/Footer/index.tsx
=> 🔨 Refactor(#273): 생성일 코드 수정

src/app/(user-menu)/mypage/application/page.tsx, src/app/(user-menu)/mypage/layout.tsx, src/app/(user-menu)/mypage/page.tsx, src/app/(user-menu)/mypage/reviews/page.tsx, src/app/(user-menu)/mypage/template/create/page.tsx, src/app/(user-menu)/mypage/template/edit/[id]/page.tsx, src/app/(user-menu)/mypage/template/page.tsx, src/app/(user-menu)/mysteady/page.tsx, src/components/_common/SideBar/index.tsx, src/constants/commonStyle.ts
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/7fd30274-eab9-49b4-b399-e6fb6cff7fde
close #280
=> 💄 Style(#280): 마이 페이지 반응형 구현

src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx, src/app/(steady)/steady/applicant/[steady_id]/layout.tsx, src/app/(steady)/steady/applicant/[steady_id]/page.tsx, src/app/(steady)/steady/applicant/layout.tsx
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/57f1e54f-2d59-4014-be1f-e71a44549aa6
close #282
=> 💄 Style(#282): 신청자 목록 및 답변 열람 페이지 반응형 구현

src/app/(steady)/(application)/application/layout.tsx, src/components/application/Title.tsx
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/6068f760-4a2e-4a76-bf21-73fa93b231d8
close #284
=> 💄 Style(#284): 신청서 생성 및 수정 페이지 반응형 구현

src/app/(steady)/steady/manage/[id]/page.tsx, src/services/steady/deleteSteadyMember.ts
- 리뷰가 있는 유저는 추방되지 않는 이슈가 있습니다 (BE에서 해결 예정)
close #271
=> ✨ Feat(#271): 스테디 멤버 추방 api 연동

src/app/(user-menu)/mypage/application/page.tsx, src/app/(user-menu)/mypage/template/page.tsx, src/components/_common/Modal/DeleteModal/index.tsx
=> ✨ Feat(#269): 내 신청서 및 템플릿 삭제 확인 모달 추가

src/app/(steady)/steady/manage/[id]/page.tsx, src/app/(user-menu)/mypage/page.tsx, src/app/(user-menu)/mysteady/page.tsx, src/components/_common/Modal/UserModal/UserItems.tsx, src/components/_common/Modal/UserModal/index.tsx
=> 💄Style(#293): 모달 반응형 구현 및 스타일링 통일

src/app/(steady)/steady/detail/[id]/page.tsx, src/app/(user-menu)/mysteady/page.tsx, src/services/types/index.ts
https://github.com/Team-Blitz-Steady/steady-client/assets/109654823/b28dcbb8-bad4-43dc-8e4f-75f02bea1c78
- 뱃지 아이콘 수정사항이 있습니다.
- 
close #287
=> ✨Feat(#287): 내 스테디 연락수단 클립 보드 구현

src/app/page.tsx
- lg:350 -> lg:h-350
close #303
=> 🚨 Fix(#303): 메인페이지 코드 수정

src/app/layout.tsx, src/app/shared-metadata.ts
=> ✨ Feat(#306): open graph 적용

src/schemas/steadySchema.ts
- FormMessage가 왜 required_error 시에만 작동할까요...?
close #333
=> 🚨 Fix(#333): 스테디 수정 시 포지션과 스택을 선택하지 않은 채로 수정이 되는 현상 수정

package.json, pnpm-lock.yaml, src/components/_common/NotificationPopup/index.tsx
알림 조회 API 변경되면 한번 더 바뀔거같습니다
close #328
=> 💄 Style(#328): 알림 컴포넌트 디자인 1차 수정
